"""Update tables and use NUMERIC

Revision ID: 1753236f8495
Revises: d701d7cab213
Create Date: 2024-11-06 12:14:35.218488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1753236f8495'
down_revision = 'd701d7cab213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_open', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('market_close', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('open_days', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('close_on_holidays', sa.Boolean(), nullable=True))

    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.alter_column('order_number',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.drop_column('close_on_holidays')
        batch_op.drop_column('open_days')
        batch_op.drop_column('market_close')
        batch_op.drop_column('market_open')

    # ### end Alembic commands ###
