"""unix-timestamps branch

Revision ID: 4007435dca96
Revises: 03914933722c
Create Date: 2024-11-10 16:20:45.395147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4007435dca96'
down_revision = '03914933722c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_unix', sa.Integer(), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_unix', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at_unix', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login_unix', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login_unix')
        batch_op.drop_column('created_at_unix')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('timestamp_unix')

    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.drop_column('timestamp_unix')

    # ### end Alembic commands ###
