"""Update AdminSettings table

Revision ID: 50e0947a59b1
Revises: 1753236f8495
Create Date: 2024-11-06 12:47:06.807559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = ''
down_revision = ''
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_open', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('market_close', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.drop_column('market_close')
        batch_op.drop_column('market_open')

    # ### end Alembic commands ###
