"""Add id primary key to StockHistory model

Revision ID: 7467b8c9f4a0
Revises: 879815c03844
Create Date: 2024-10-20 14:25:19.902154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7467b8c9f4a0'
down_revision = '879815c03844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.create_unique_constraint(None, ['order_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('order_number',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
