"""Add open, close, high, low prices and volume to Stock and StockHistory

Revision ID: bdd7f5b37614
Revises: a94582e9d50b
Create Date: 2024-11-12 12:27:18.153404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd7f5b37614'
down_revision = 'a94582e9d50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('close_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('high_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('low_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('volume', sa.Integer(), nullable=True))

    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('close_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('high_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('low_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('volume', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.drop_column('volume')
        batch_op.drop_column('low_price')
        batch_op.drop_column('high_price')
        batch_op.drop_column('close_price')
        batch_op.drop_column('open_price')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('volume')
        batch_op.drop_column('low_price')
        batch_op.drop_column('high_price')
        batch_op.drop_column('close_price')
        batch_op.drop_column('open_price')

    # ### end Alembic commands ###
