"""Add first names and last names to User model

Revision ID: d701d7cab213
Revises: 9b569d065b84
Create Date: 2024-10-28 12:52:58.881581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd701d7cab213'
down_revision = '9b569d065b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False, server_default='First Name'))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False, server_default='Last Name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')


    # ### end Alembic commands ###
